// <auto-generated />
using ElectricShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricShop.Migrations
{
    [DbContext(typeof(ElectricDbContext))]
    [Migration("20260402110411_CreateElectricDb")]
    partial class CreateElectricDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ElectricShop.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Memory")
                        .HasColumnType("int");

                    b.Property<int>("OperationSystemId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OperationSystemId");

                    b.ToTable("computers");
                });

            modelBuilder.Entity("ElectricShop.Models.OperationSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("operationSystems");
                });

            modelBuilder.Entity("ElectricShop.Models.Computer", b =>
                {
                    b.HasOne("ElectricShop.Models.OperationSystem", "OperationSystem")
                        .WithMany("computers")
                        .HasForeignKey("OperationSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationSystem");
                });

            modelBuilder.Entity("ElectricShop.Models.OperationSystem", b =>
                {
                    b.Navigation("computers");
                });
#pragma warning restore 612, 618
        }
    }
}
